In [18]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPool2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense

In [2]:
#here we are loading the data

(X_train, y_train), (X_test, y_test) = mnist.load_data()


11490434/11490434 [==============================] - 223s 19us/step


In [19]:
#here we are reshaping the data
X_train = X_train.reshape((X_train.shape[0]), X_train.shape[1], X_train.shape[2],1)

In [20]:
X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], X_test.shape[2],1))

In [21]:
#here we are checking the shape after reshape

print(X_train.shape)
print(X_test.shape)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [22]:
#and here we are normalizing the pixel values
print(X_train)
print(X_test)

[[[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 [[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 [[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 ...


 [[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]

In [23]:
print(y_train)
print(y_test)

[5 0 4 ... 5 6 8]
[7 2 1 ... 4 5 6]


In [24]:
model = Sequential()

In [25]:
model.add(Conv2D(32,(3,3), activation='relu', input_shape=(28,28,1)))

In [26]:
model.add(MaxPool2D(2,2))

In [27]:
#adding fully connected layer

model.add(Flatten())
model.add(Dense(100, activation='relu'))

In [28]:
#adding output layer

model.add(Dense(10, activation='softmax'))

In [29]:
#compiling the model
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics = ['accuracy'])

In [30]:
#fitting the model
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 25s 13ms/step - loss: 0.3988 - accuracy: 0.9301
Epoch 2/10
1875/1875 [==============================] - 24s 13ms/step - loss: 0.0819 - accuracy: 0.9760
Epoch 3/10
1875/1875 [==============================] - 25s 13ms/step - loss: 0.0587 - accuracy: 0.9819
Epoch 4/10
1875/1875 [==============================] - 24s 13ms/step - loss: 0.0458 - accuracy: 0.9856
Epoch 5/10
1875/1875 [==============================] - 25s 13ms/step - loss: 0.0348 - accuracy: 0.9891
Epoch 6/10
1875/1875 [==============================] - 25s 13ms/step - loss: 0.0296 - accuracy: 0.9907
Epoch 7/10
1875/1875 [==============================] - 25s 13ms/step - loss: 0.0268 - accuracy: 0.9916
Epoch 8/10
1875/1875 [==============================] - 25s 13ms/step - loss: 0.0204 - accuracy: 0.9934
Epoch 9/10
1875/1875 [==============================] - 25s 13ms/step - loss: 0.0199 - accuracy: 0.9941
Epoch 10/10
1875/1875 [==============================] - 26s 14m

In [31]:
#evaluating the model

model.evaluate(X_test, y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.1262 - accuracy: 0.9782


[0.12619581818580627, 0.9782000184059143]